apps:
  gmail-archiver:
    command: 'bin/gmail-archiver'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/gmail-archiver/issues'
description: 'Locally archive Gmail emails.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/gmail-archiver/issues'
license: 'MIT'
name: 'gmail-archiver'
parts:
  gmail-archiver:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/gmail-archiver'
summary: 'Locally archive Gmail emails.'
title: 'gmail-archiver'
version: '0.1.0'
website: 'https://tatsh.github.io/gmail-archiver/'
